// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fywlwgnowybwzgljygdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5d2x3Z25vd3lid3pnbGp5Z2R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NzU5MjIsImV4cCI6MjA2NzI1MTkyMn0.T_pl0ZOaLaxQNR42CKM8rSybxOVv_YO35HJWpaHSIS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});